import Image from "next/image";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Home() {
  return <div className="flex"></div>;
}
